# Generated by Django 4.1.7 on 2023-04-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Category',
        ),
    ]
